feat(migration): migration des courriers
SocialGouv/domifa pull request #1945
Opened 2021-12-09 17:16 UTC by pYassine

2021-12-21 14:53 UTC, pibouu requested changes

2021-12-21 14:53 UTC, pibouu commented on packages/backend/src/interactions/services/interactionsCreator.service.ts
> +  console.log(oppositeType);
enlever le console.log

2021-12-21 14:53 UTC, ghost commented on packages/backend/src/interactions/services/interactionsCreator.service.ts
> +  console.log({
enlever le console.log

2021-12-21 14:53 UTC, ghost commented on packages/backend/src/interactions/services/interactionsCreator.service.ts
> +  console.log(updatedInteractions);
pareil

2021-12-21 14:53 UTC, pibouu commented on packages/backend/src/_migrations/1638808597232-migrate-interactions.migration.ts
> +            lastInteractionCalculated[interaction.type] =
pour plus de lisibilité

lastInteractionCalculated[interaction.type] += interaction.nbCourrier;

2021-12-21 14:53 UTC, ghost commented on packages/backend/src/_migrations/1638808597232-migrate-interactions.migration.ts
> +              lastInteractionCalculated[oppositeType] =
lastInteractionCalculated[oppositeType] -= interaction.nbCourrier

2021-12-21 14:53 UTC, ghost commented on packages/backend/src/database/services/interaction/interactionRepository.service.ts
> +  console.log(results);
enlever console.log

2021-12-21 14:53 UTC, pibouu commented on packages/backend/src/database/services/interaction/interactionRepository.service.ts
> +  console.log(results);
enlever console.log

2021-12-21 14:53 UTC, pibouu commented on packages/backend/src/database/services/interaction/interactionRepository.service.ts
> +  if (typeof results[0] === "undefined") {
ça ne peut que être undefined ? ça ne peut pas être null

2021-12-21 14:53 UTC, pibouu commented on packages/backend/src/database/services/interaction/interactionRepository.service.ts
> +  return typeof results[0] === "undefined"
ça ne peut que être undefined ? ça ne peut pas être null

2021-12-21 14:53 UTC, pibouu commented on packages/backend/src/interactions/services/interactionsCreator.service.ts
> +    console.log(pendingInteractionsCount);
enlever le console.log

2021-12-21 14:53 UTC, pibouu commented on packages/backend/src/interactions/services/interactionsCreator.service.ts
>    } else {
transformer en else if (interaction.type === "visite" || interaction.type === "appel")

2021-12-21 17:44 UTC, pYassine commented on packages/backend/src/interactions/services/interactionsCreator.service.ts
>    } else {
@pibouu  y'a les NPAI aussi

2021-12-22 11:01 UTC, revolunet approved these changes

2021-12-23 15:23 UTC, closed without merging