feat: new stats sms page back office
SocialGouv/domifa pull request #2025
Opened 2022-01-11 17:11 UTC by pibouu

2022-01-13 08:49 UTC, pYassine requested changes

2022-01-13 08:49 UTC, pYassine commented on packages/backend/src/_common/model/interaction/InteractionType.type.ts
> +export type InteractionTypeStats =
Type à mettre dans un autre fichier, reprendre le type avec les SmsId du backend

2022-01-13 08:49 UTC, pYassine commented on packages/backend/src/_common/model/stats/StatsPeriod.type.ts
> +export type Period = "days" | "months";
Nom du fichier = nom du type --> StatsPeriod

2022-01-13 08:49 UTC, pYassine commented on packages/backend/src/_portail-admin/admin-sms/controllers/admin-sms.controller.ts
> +@UseGuards(AuthGuard("jwt"), AppUserGuard)
@pibouu on pourrait pas rassembler tout ce qui touche à l'admin de SMS dans un controller ? (stats + activation)

2022-01-13 08:49 UTC, pYassine commented on packages/backend/src/util/structureSms.service.ts
> +    (structureSms.enabledByDomifa || structureSms.enabledByStructure) &&
@pibouu tes 2 if font la même chose, pourrait-on simplifier, c'est pas très clair

2022-01-13 08:49 UTC, pYassine commented on packages/portail-admins/src/_common/stats/StatsSms.type.ts
> +export type Period = "days" | "months";
@pibouu si tu peux diviser en fichiers, ou juste copier-coller ceux en front comme ça on garde l'organisation d'un fichier = un type

2022-01-13 08:49 UTC, pYassine commented on packages/portail-admins/src/app/modules/admin-sms/components/admin-sms-stats/admin-sms-stats.component.ts
> +  public echeanceDeuxMois30: any[];
@pibouu il faudrait typer le format des stats

2022-01-17 13:29 UTC, pibouu commented on packages/backend/src/util/structureSms.service.ts
> +    (structureSms.enabledByDomifa || structureSms.enabledByStructure) &&
Ce ne sont pas les mêmes condition, la première vérifie si les 2 variables sont bien à true enabledByDomifa && enabledByStructure (d'après l'explication que j'ai eu sur l'activation des sms par Anne Laure).

Et le deuxième if si l'une ou l'autre est true enabledByDomifa || enabledByStructure ça va mettre une date de désactivation.

2022-01-17 13:29 UTC, pibouu commented on packages/backend/src/_portail-admin/admin-sms/controllers/admin-sms.controller.ts
> +@UseGuards(AuthGuard("jwt"), AppUserGuard)
Qu'est ce que tu entends par activation ?

2022-01-25 15:15 UTC, pYassine approved these changes

2022-01-25 15:15 UTC, merged