test11
SocialGouv/domifa pull request #2220
Opened 2022-04-20 14:09 UTC by ErceauFloriane

2022-05-10 09:56 UTC, pYassine requested changes

2022-05-10 09:56 UTC, pYassine commented on packages/frontend/src/app/app.component.html
> +          href="plandusite"
Remplacer par un routerlink
Créer la page "plan du site"

2022-05-10 09:56 UTC, pYassine commented on packages/frontend/src/app/modules/general/components/navbar/navbar.component.html
> +          <li>
- Remplacer les href par des routerlink
- Trouver le chemin de la page actuelle : 
- Ajouter le fragment #page dans le routerlink
https://stackoverflow.com/questions/36101756/angular2-routing-with-hashtag-to-page-anchor

2022-05-10 09:56 UTC, pYassine commented on packages/frontend/src/app/modules/usagers/components/manage/manage-usagers-table/manage-usagers-table.html
> +            <button class="icon-passage list-icon"></button>
Titre manquant

2022-05-10 09:56 UTC, pYassine commented on packages/frontend/src/app/modules/usagers/components/manage/manage-usagers-table/manage-usagers-table.html
> +            <button autofocus class="icon-courrier list-icon"></button>
Title manquant

2022-05-10 09:56 UTC, pYassine commented on packages/frontend/src/app/modules/usagers/components/manage/manage-usagers-table/manage-usagers-table.html
> +            <button autofocus class="icon-courrier list-icon"></button>
Autofocus à retirer

2022-05-10 09:56 UTC, pYassine commented on packages/frontend/src/app/modules/usagers/components/manage/manage-usagers-table/manage-usagers-table.html
> +            <button autofocus class="icon-courrier list-icon"></button>
Ajouter une bordure lorsqu'on se focus sur les bouton de réception, appel , passage

2022-05-13 11:50 UTC, ErceauFloriane commented on packages/frontend/src/app/app.component.html
> +          href="plandusite"
Done --> https://domifa-feat-rgaa-test.dev.fabrique.social.gouv.fr/

2022-05-13 11:50 UTC, ErceauFloriane commented on packages/frontend/src/app/modules/usagers/components/manage/manage-usagers-table/manage-usagers-table.html
> +            <button class="icon-passage list-icon"></button>
Done -->

2022-05-13 11:50 UTC, ErceauFloriane commented on packages/frontend/src/app/modules/usagers/components/manage/manage-usagers-table/manage-usagers-table.html
> +            <button autofocus class="icon-courrier list-icon"></button>
Done --> https://domifa-feat-rgaa-test.dev.fabrique.social.gouv.fr/

2022-05-13 11:54 UTC, ErceauFloriane commented
Url pour tester --> https://domifa-feat-rgaa-test.dev.fabrique.social.gouv.fr/

2022-05-17 05:57 UTC, closed without merging