Sre/kontinuous
SocialGouv/domifa pull request #2620
Opened 2023-01-24 15:06 UTC by achauve

2023-01-24 15:17 UTC, pYassine commented on .github/workflows/preproduction.yml
> +  workflow_dispatch:
@achauve à supprimer, on doit pas pouvoir choisir la branche qu'on déploie en préprod. C'est master systématiquement

2023-01-24 15:17 UTC, pYassine commented on .github/workflows/production.yml
> +  workflow_dispatch:
@achauve à supprimer, on doit pas pouvoir choisir la branche qu'on déploie en préprod. C'est master systématiquement

2023-01-24 15:18 UTC, pYassine commented on packages/backend/package.json
> +    "start:prod": "scripts/start",
A retirer, le script ne doit pas être lancé par yarn

2023-01-24 15:19 UTC, achauve commented on .kontinuous/env/prod/templates/azure-domifa-volume.sealed-secret.yaml
> +apiVersion: bitnami.com/v1alpha1
virer dossier kube workflow

2023-01-25 08:26 UTC, pYassine requested changes
Il reste "workflow_dispatch" à retirer ainsi que le script dans "packages/backent/package.json" Sinon c'est good pour moi @achauve !

2023-01-26 14:17 UTC, achauve commented on .github/workflows/preproduction.yml
> +  workflow_dispatch:
mais ajouter workflow_dispatch permet juste de trigger manuellement, pas de choisir la branche (si l'input branch n'a pas été définie)

2023-01-26 14:17 UTC, achauve commented on .github/workflows/production.yml
> +  workflow_dispatch:
idem

2023-01-31 08:36 UTC, pYassine approved these changes

2023-01-31 16:28 UTC, devthejo approved these changes

2023-01-31 18:47 UTC, merged